---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.4
  name: csidrivers.k8s.v6d.io
spec:
  group: k8s.v6d.io
  names:
    kind: CSIDriver
    listKind: CSIDriverList
    plural: csidrivers
    singular: csidriver
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusters:
                default: []
                items:
                  properties:
                    name:
                      default: ""
                      type: string
                    namespace:
                      default: ""
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
                type: array
              enableToleration:
                default: false
                type: boolean
              enableVerboseLog:
                default: false
                type: boolean
              image:
                default: vineyardcloudnative/vineyard-operator
                type: string
              imagePullPolicy:
                default: IfNotPresent
                type: string
              sidecar:
                default:
                  attacherImage: registry.k8s.io/sig-storage/csi-attacher:v4.0.0
                  enableTopology: false
                  imagePullPolicy: Always
                  livenessProbeImage: registry.k8s.io/sig-storage/livenessprobe:v2.8.0
                  nodeRegistrarImage: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.0
                  provisionerImage: registry.k8s.io/sig-storage/csi-provisioner:v3.3.0
                properties:
                  attacherImage:
                    default: registry.k8s.io/sig-storage/csi-attacher:v4.0.0
                    type: string
                  enableTopology:
                    default: false
                    type: boolean
                  imagePullPolicy:
                    default: Always
                    type: string
                  livenessProbeImage:
                    default: registry.k8s.io/sig-storage/livenessprobe:v2.8.0
                    type: string
                  nodeRegistrarImage:
                    default: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.0
                    type: string
                  provisionerImage:
                    default: registry.k8s.io/sig-storage/csi-provisioner:v3.3.0
                    type: string
                required:
                - attacherImage
                - enableTopology
                - imagePullPolicy
                - livenessProbeImage
                - nodeRegistrarImage
                - provisionerImage
                type: object
              storageClassName:
                default: vineyard-csi
                type: string
              volumeBindingMode:
                default: WaitForFirstConsumer
                type: string
            required:
            - clusters
            - enableToleration
            - enableVerboseLog
            - image
            - imagePullPolicy
            - sidecar
            - storageClassName
            - volumeBindingMode
            type: object
          status:
            properties:
              state:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
